### ISSUE TITLE
NineML parsing fails on python 2.7 (at least on Mac OS X 10.6.8 with Fink)

### ISSUE THREAD

**Issue by robclewley** [tclose/nineml#9]
Traceback:

/Users/robclewley/examples/NineML_import_test.py in test_Izh_FS(Iexts)
    336 def test_Izh_FS(Iexts=None):
    337     """Izhikevich Fast Spiker model"""
--> 338     c = get_Izh_FS_component()
    339 
    340     # Convert to PyDSTool.ModelSpec and create HybridModel object

/Users/robclewley/examples/NineML_import_test.py in get_Izh_FS_component()
     83     Abstraction Layer of Python API.
     84     """
---> 85     return nineml.read('NineML_Izh_FS.xml')['Izh_FS']
     86 
     87 def get_aeIF_component():

/sw/lib/python2.7/site-packages/9ML-0.3.dev0-py2.7.egg/nineml/document.pyc in read(url, relative_to)
    328                                  .format(url, e))
    329     root = xml.getroot()
--> 330     return load(root, url)
    331 
    332 

/sw/lib/python2.7/site-packages/9ML-0.3.dev0-py2.7.egg/nineml/document.pyc in load(root_element, read_from)
    301                     have been read from in order to resolve relative references
    302     """
--> 303     return Document.from_xml(root_element, url=read_from)
    304 
    305 

/sw/lib/python2.7/site-packages/9ML-0.3.dev0-py2.7.egg/nineml/document.pyc in from_xml(cls, element, url)
    236     def from_xml(cls, element, url=None):
    237         if element.tag != NINEML + cls.element_name:
--> 238             raise Exception("Not a NineML root ('{}')".format(element.tag))
    239         # Initialise the document

    240         elements = {'_url': url}

Exception: Not a NineML root ('{http://nineml.org/9ML/0.2}NineML')

**Comment by tclose** [comment]
You will need to update the xml namespace to _http://nineml.net/9ML/1.0_ (we will have to add some handling for different versions in there at some point).

**Comment by robclewley** [comment]
Thanks, but I have no idea where that is set.

**Comment by tclose** [comment]
It is actually in the XML file you are reading as an 'xmlns' attribute of
the NineML element. Cheers

On 2 March 2015 at 12:15, Robert Clewley <notifications@github.com> wrote:

>  Thanks, but I have no idea where that is set.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tclose/nineml/issues/9#issuecomment-76653108>.
>



-- 
Thomas G. Close, PhD.
Postdoctoral Researcher,
Computational Neuroscience Unit,
Okinawa Institute of Science and Technology
e: tclose@oist.jp
w: +81 98 966 8804

**Comment by robclewley** [comment]
Right, I forgot to check there :) Thanks. I was confused because I knew it was already set correctly in the egg's nineml/xmlns.py
